export type RentalCategoryOption = {
  label: string;
  href: string;
  aliases?: string[];
};

type RentalCategoryGroup = {
  id: RentalCategoryGroupId;
  href: string;
  labels: string[];
  extraAliases?: string[];
  signals?: string[];
};

type RentalCategoryGroupId = "western" | "ethnic" | "bridal";

const RENTAL_CATEGORY_GROUPS = [
  {
    id: "western",
    href: "/rentals/western",
    labels: [
      "Western Wear",
      "Dresses",
      "Frock Dresses",
      "Bodycon Dresses",
      "Gowns",
      "Slit Gowns",
      "Cape Gowns",
      "Western Saree Dresses",
      "Maxi Dresses",
      "Mini Dresses",
      "Mermaid Gowns",
      "Celebrity Styles",
    ],
    extraAliases: ["Western", "Western Dresses", "Occasion Dresses", "Celebrity Looks"],
    signals: ["modern", "western"],
  },
  {
    id: "ethnic",
    href: "/rentals/ethnic",
    labels: [
      "Traditional Wear",
      "Sarees",
      "Lehengas",
      "Indo Western",
      "Salwar Suits",
      "Kurtis & Sets",
      "Anarkalis",
      "Lehenga Saree",
      "Heavy Gowns",
      "Mehndi Outfits",
      "Haldi Outfits",
    ],
    extraAliases: ["Traditional", "Ethnic", "Ethnic Wear", "Festive Wear", "Wedding Wear", "Occasion Wear", "Saree", "Lehenga", "Kurti", "Gown", "Gowns", "Poshak"],
    signals: ["traditional", "ethnic"],
  },
  {
    id: "bridal",
    href: "/rentals/bridal",
    labels: [
      "Bridal Specials",
      "Bridal Lehengas",
      "Engagement Gowns",
      "Reception Gowns",
      "Reception Saree",
      "Mehndi & Haldi Outfits",
      "Sangeet Dresses",
      "Bridal Sarees",
      "Rajasthani Poshak",
    ],
    extraAliases: ["Wedding Wear", "Bridal Wear", "Traditional Bridal", "Occasion Wear"],
    signals: ["traditional", "bridal", "wedding"],
  },



] as const satisfies readonly RentalCategoryGroup[];

export const RENTAL_CATEGORY_OPTIONS: RentalCategoryOption[] = RENTAL_CATEGORY_GROUPS.flatMap((group) =>
  group.labels.map((label) => ({
    label,
    href: group.href,
    aliases: [],
  }))
);

export const RENTAL_SIZE_OPTIONS = ["XS", "S", "M", "L", "XL", "XXL", "3XL", "4XL", "Free Size"];

export const RENTAL_COLOR_OPTIONS = [
  "Multi Color",
  "Red",
  "Pink",
  "Light Pink",
  "Hot Pink",
  "Rose Pink",
  "Blue",
  "Sky Blue",
  "Light Blue",
  "Royal Blue",
  "Powder Blue",
  "Green",
  "Light Green",
  "Sea Green",
  "Lime Green",
  "Forest Green",
  "Yellow",
  "Light Yellow",
  "Lemon Yellow",
  "Black",
  "White",
  "Purple",
  "Light Purple",
  "Lilac",
  "Orange",
  "Burnt Orange",
  "Maroon",
  "Gold",
  "Silver",
  "Brown",
  "Dark Brown",
  "Coffee Brown",
  "Chocolate Brown",
  "Tan",
  "Camel",
  "Beige",
  "Cream",
  "Ivory",
  "Grey",
  "Light Grey",
  "Charcoal",
  "Navy",
  "Teal",
  "Turquoise",
  "Aqua",
  "Cyan",
  "Mint",
  "Olive",
  "Peach",
  "Light Peach",
  "Coral",
  "Lavender",
  "Magenta",
  "Mustard",
  "Rust",
  "Wine",
  "Burgundy",
  "Plum",
  "Mauve",
  "Periwinkle",
  "Champagne",
  "Rose Gold",
  "Copper",
  "Off White",
  "Nude",
  "Khaki",
  "Emerald",
  "Sage Green",
  "Mint Green",
  "Pastel Pink",
  "Pastel Blue",
  "Pastel Green",
  "Pastel Yellow",
].sort((a, b) => a.localeCompare(b));

export const RENTAL_CITY_OPTIONS = [
  "India",
  "Agra",
  "Ahmedabad",
  "Ajmer",
  "Aligarh",
  "Allahabad",
  "Amritsar",
  "Aurangabad",
  "Bengaluru",
  "Bhopal",
  "Bhubaneswar",
  "Bikaner",
  "Chandigarh",
  "Chennai",
  "Coimbatore",
  "Cuttack",
  "Dehradun",
  "Delhi",
  "Dhanbad",
  "Faridabad",
  "Ghaziabad",
  "Goa",
  "Gorakhpur",
  "Gurugram",
  "Guwahati",
  "Gwalior",
  "Hubli",
  "Hyderabad",
  "Indore",
  "Jabalpur",
  "Jaipur",
  "Jalandhar",
  "Jammu",
  "Jamshedpur",
  "Jodhpur",
  "Kanpur",
  "Kochi",
  "Kolkata",
  "Kota",
  "Lucknow",
  "Ludhiana",
  "Madurai",
  "Mangalore",
  "Meerut",
  "Mohali",
  "Mumbai",
  "Mysuru",
  "Nagpur",
  "Nashik",
  "Noida",
  "Patna",
  "Prayagraj",
  "Pune",
  "Raipur",
  "Rajkot",
  "Ranchi",
  "Siliguri",
  "Surat",
  "Thane",
  "Thiruvananthapuram",
  "Udaipur",
  "Vadodara",
  "Varanasi",
  "Vijayawada",
  "Visakhapatnam",
];
